### ISSUE TITLE
Fix the truncated date

### ISSUE THREAD

**Issue by gurrrung** [Tele-Bots/CovidBot#102]
![Screenshot from 2021-04-20 08-45-17](https://user-images.githubusercontent.com/30543444/115332198-f1eda280-a1b4-11eb-91aa-1dd17d5dbaa5.png)

Suggest the changes before making PR.

**Comment by nikhilm2302** [comment]
Hi @gurrrung, The problem is with the substring function you used for the date, I would recommend to not use the substring function at all since it doesn't make much sense to have it if you want the whole data which you are anyways getting from the API or to use it like this `date = date.substring(0, date.length);` which again doesn't make much sense since you would be getting the whole date anyways.

Sample permalink to the buggy line: https://github.com/Tele-Bots/CovidBot/blob/d047952a4aeec3a406f1d13ab4e9597be6a966b3/app/utils/prepareAnswer.js#L132

There are many more instances of this throughout the prepareAnswer.js file.

**Comment by gurrrung** [comment]
@nikhilm2302 Thanks for investigating. I am looking to show only the date and month without the year because it's obvious. PRs are welcome.
